-- MySQL Script generated by MySQL Workbench
-- Thu 03 Jul 2014 03:45:56 PM CDT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fifa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `fifa` ;
CREATE SCHEMA IF NOT EXISTS `fifa` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `fifa` ;

-- -----------------------------------------------------
-- Table `fifa`.`continente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fifa`.`continente` ;

CREATE TABLE IF NOT EXISTS `fifa`.`continente` (
  `id_continente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_continente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fifa`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fifa`.`pais` ;

CREATE TABLE IF NOT EXISTS `fifa`.`pais` (
  `id_pais` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `bandera` VARCHAR(45) NULL,
  `id_continente` INT NOT NULL,
  PRIMARY KEY (`id_pais`),
  INDEX `fkContinente_idx` (`id_continente` ASC),
  CONSTRAINT `fkPais`
    FOREIGN KEY (`id_continente`)
    REFERENCES `fifa`.`continente` (`id_continente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fifa`.`equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fifa`.`equipo` ;

CREATE TABLE IF NOT EXISTS `fifa`.`equipo` (
  `id_equipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `id_pais` INT NOT NULL,
  `escudo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_equipo`),
  INDEX `fk1Pais_idx` (`id_pais` ASC),
  CONSTRAINT `fk1Equipo`
    FOREIGN KEY (`id_pais`)
    REFERENCES `fifa`.`pais` (`id_pais`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fifa`.`integrante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fifa`.`integrante` ;

CREATE TABLE IF NOT EXISTS `fifa`.`integrante` (
  `id_integrante` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(100) NULL,
  `peso` FLOAT NULL,
  `estatura` FLOAT NULL,
  `foto` VARCHAR(50) NULL,
  `edad` INT NULL,
  `id_equipo` INT NOT NULL,
  PRIMARY KEY (`id_integrante`),
  INDEX `fkIntegrante_idx` (`id_equipo` ASC),
  CONSTRAINT `fkIntegrante`
    FOREIGN KEY (`id_equipo`)
    REFERENCES `fifa`.`equipo` (`id_equipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `fifa`.`posicion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fifa`.`posicion` ;

CREATE TABLE IF NOT EXISTS `fifa`.`posicion` (
  `id_posicion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `abreviatura` VARCHAR(45) NULL,
  PRIMARY KEY (`id_posicion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fifa`.`jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fifa`.`jugador` ;

CREATE TABLE IF NOT EXISTS `fifa`.`jugador` (
  `id_jugador` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NULL,
  `id_integrante` INT NOT NULL,
  `id_posicion` INT NOT NULL,
  INDEX `fk2Jugador_idx` (`id_posicion` ASC),
  PRIMARY KEY (`id_jugador`),
  CONSTRAINT `fk1Jugador`
    FOREIGN KEY (`id_integrante`)
    REFERENCES `fifa`.`integrante` (`id_integrante`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk2Jugador`
    FOREIGN KEY (`id_posicion`)
    REFERENCES `fifa`.`posicion` (`id_posicion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fifa`.`entrenador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fifa`.`entrenador` ;

CREATE TABLE IF NOT EXISTS `fifa`.`entrenador` (
  `id_entrenador` INT NOT NULL AUTO_INCREMENT,
  `id_pais` INT NOT NULL,
  INDEX `fk1Entrenador_idx` (`id_pais` ASC),
  INDEX `fk2Entrenador_idx` (`id_entrenador` ASC),
  PRIMARY KEY (`id_entrenador`),
  CONSTRAINT `fk1Entrenador`
    FOREIGN KEY (`id_pais`)
    REFERENCES `fifa`.`pais` (`id_pais`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk2Entrenador`
    FOREIGN KEY (`id_entrenador`)
    REFERENCES `fifa`.`integrante` (`id_integrante`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fifa`.`ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fifa`.`ciudad` ;

CREATE TABLE IF NOT EXISTS `fifa`.`ciudad` (
  `id_ciudad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `id_pais` INT NOT NULL,
  PRIMARY KEY (`id_ciudad`),
  INDEX `fkPais_idx` (`id_pais` ASC),
  CONSTRAINT `fkCiudad`
    FOREIGN KEY (`id_pais`)
    REFERENCES `fifa`.`pais` (`id_pais`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fifa`.`estadio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fifa`.`estadio` ;

CREATE TABLE IF NOT EXISTS `fifa`.`estadio` (
  `id_estadio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `id_ciudad` INT NOT NULL,
  PRIMARY KEY (`id_estadio`),
  INDEX `fkEstadio_idx` (`id_ciudad` ASC),
  CONSTRAINT `fkEstadio`
    FOREIGN KEY (`id_ciudad`)
    REFERENCES `fifa`.`ciudad` (`id_ciudad`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fifa`.`juego`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fifa`.`juego` ;

CREATE TABLE IF NOT EXISTS `fifa`.`juego` (
  `id_juego` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `id_equipo_local` INT NOT NULL,
  `id_equipo_visitante` INT NOT NULL,
  `id_estadio` INT NOT NULL,
  PRIMARY KEY (`id_juego`),
  INDEX `fk1Juego_idx` (`id_estadio` ASC),
  INDEX `fk2Juego_idx` (`id_equipo_local` ASC),
  INDEX `fk3Juego_idx` (`id_equipo_visitante` ASC),
  CONSTRAINT `fk1Juego`
    FOREIGN KEY (`id_estadio`)
    REFERENCES `fifa`.`estadio` (`id_estadio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk2Juego`
    FOREIGN KEY (`id_equipo_local`)
    REFERENCES `fifa`.`equipo` (`id_equipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk3Juego`
    FOREIGN KEY (`id_equipo_visitante`)
    REFERENCES `fifa`.`equipo` (`id_equipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `fifa`.`goles_Jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fifa`.`goles_jugador` ;

CREATE TABLE IF NOT EXISTS `fifa`.`goles_jugador` (
  `id_resultado` INT NOT NULL AUTO_INCREMENT,
  `minuto_gol` TIME NULL,
  `id_juego` INT NOT NULL,
  `id_jugador` INT NOT NULL,
  PRIMARY KEY (`id_resultado`),
  INDEX `fk_resultado_1_idx` (`id_juego` ASC),
  INDEX `fk_goles_jugador_1_idx` (`id_jugador` ASC),
  CONSTRAINT `fk_resultado_1`
    FOREIGN KEY (`id_juego`)
    REFERENCES `fifa`.`juego` (`id_juego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_goles_jugador_1`
    FOREIGN KEY (`id_jugador`)
    REFERENCES `fifa`.`jugador` (`id_jugador`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fifa`.`tarjetas_jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fifa`.`tarjetas_jugador` ;

CREATE TABLE IF NOT EXISTS `fifa`.`tarjetas_jugador` (
  `id_tarjeta_jugador` INT NOT NULL AUTO_INCREMENT,
  `minuto_tarjeta` TIME NOT NULL,
  `id_juego` INT NOT NULL,
  `id_jugador` INT NOT NULL,
  `tipo_tarjeta` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_tarjeta_jugador`),
  INDEX `fk_resultado_1_idx` (`id_juego` ASC),
  INDEX `fk_golesJugador_1_idx` (`id_jugador` ASC),
  CONSTRAINT `fk_resultado_10`
    FOREIGN KEY (`id_juego`)
    REFERENCES `fifa`.`juego` (`id_juego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_goles_jugador_10`
    FOREIGN KEY (`id_jugador`)
    REFERENCES `fifa`.`jugador` (`id_jugador`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
